import Head from 'next/head'
import {MdOutlineDarkMode} from 'react-icons/md'
import {BsFacebook} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image'
import character from '../public/face1.jpg'
import web from '../public/web.png'
import graphics from '../public/graphics.png'
import coding from '../public/coding.png'
import website3 from '../public/website3.jpg'
import website4 from '../public/website4.jpg'
import work2 from '../public/work certificate.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode? 'dark' : ''}>
      <Head>
        <title>Manoj Tamang Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ice.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800'>

        <section className='min-h-screen'>

          <nav className='py-4 flex justify-between'>
            <div className='text-2xl py-2 md:text-3xl  dark:text-white'>MT®—22</div>  
            <ul className='flex items-center'>
              <li><MdOutlineDarkMode onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-4xl dark:text-gray-400' /></li>
              <li><a
                    href='https://drive.google.com/file/d/1jeG-E0mDMX4MKaUOJrH6LYiLWcEE_GNb/view?usp=sharing'
                    target={'_blank'}
                    className='bg-blue-400 text-white rounded-l-full rounded-r-full px-4 py-2 ml-8'
                    >GET RESUME
                  </a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-4'>
            <h2 className='font-serif text-4xl py-2 text-blue-400 font-medium md:text-6xl'>Manoj Tamang</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Front-End Developer</h3>
            <p className='text-md py-2 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400'>
              Undergraduate student of computer science. Seeking to pursue a career in technical field.
            </p>
          </div>
          

          <div className='text-5xl py-5 text-gray-800 flex justify-center gap-8 dark:text-gray-400'>
            <a href='https://twitter.com/manojtamang2000' target={'_blank'}><AiFillTwitterCircle/></a>
            <a href='https://www.facebook.com/ManojTamang2000' target={'_blank'}><BsFacebook /></a>
            <a href='https://www.linkedin.com/in/manoj-tamang-ab3797250/' target={'_blank'}><AiFillLinkedin /></a>
          </div>


          <div className='mx-auto bg-gradient-to-b from-blue-700 rounded-full w-48 h-48 relative overflow-hidden m-4 md:h-60 md:w-60'>
            <Image src={character} layout='fill' objectFit='cover' />
          </div>

        </section>



        <section className='dark:text-gray-400'>

          <div className='shadow-2xl rounded-2xl p-10'>
            <h3 className='font-serif text-3xl py-1'>Services I Offer</h3>
            <p className='text-md md:text-xl py-5 leading-8'>
              I concentrate in building front-end applications and digital product design. I enjoy creating effortless user experience and designing delightful digital products.
              I always seek new opportunities for co-operation on projects around interesting dashboards, design systems or landing pages. Let's create something awesome together!
            </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center shadow-2xl rounded-2xl p-10 my-10 transition-all hover:scale-105'>
              <Image src={web} height={100} width={100} />
              <h3 className='text-lg font-medium pt-8 text-blue-700'>Front-End Development</h3>
              <p>React</p>
              <p>JavaScript</p>
              <p>CSS</p>
            </div>
            <div className='text-center shadow-2xl rounded-2xl p-10 my-10 transition-all hover:scale-105'>
              <Image src={graphics} height={100} width={100} />
              <h3 className='text-lg font-medium pt-8 text-blue-700'>Graphic Design</h3>
              <p>Photoshop</p>
              <p>Illustrator</p>
              <p>Figma</p>
            </div>
            <div className='text-center shadow-2xl rounded-2xl p-10 my-10 transition-all hover:scale-105'>
              <Image src={coding} height={100} width={100} />
              <h3 className='text-lg font-medium pt-8 text-blue-700'>Programming Languages</h3>
              <p>Python</p>
              <p>C</p>
              <p>C++</p>
            </div>
          </div>
        </section>




        <section className='shadow-2xl rounded-2xl p-10'>
          <div className='dark:text-gray-400'>
            <h3 className='font-serif text-3xl '>Portfolio</h3>
            <p className='text-md md:text-xl py-5 leading-8'>
              Web and graphic design sure is fun to do! Here are a handful of items from my portfolio over the last few months.
            </p>
          </div>

          <div className='flex flex-col gap-10 md:flex-row md:flex-wrap'>
            <div className='basis-1/3 transition-all hover:scale-105 grayscale hover:grayscale-0'>
              <Image src={website3} className='rounded-2xl object-cover w-full h-full' />
            </div>
            <div className='basis-1/3 transition-all hover:scale-105 grayscale hover:grayscale-0'>
              <Image src={website4} className='rounded-2xl object-cover w-full h-full' />
            </div>
            <div className='basis-1/3 transition-all hover:scale-105 grayscale hover:grayscale-0'>
              <Image src={work2} className='rounded-2xl object-cover w-full h-full' />
            </div>
          </div>
        </section>

        <section>

          <h2 className='font-serif text-center text-2xl md:text-3xl py-10 text-blue-400 font-medium'>
            I occasionally take on freelance opportunities.
          </h2>

          <div className='pb-10 text-center'>
            <a
              href='mailto:yonjantamang5@gmail.com'
              className='bg-gradient-to-l from-blue-400 to-gray-700 text-white px-4 py-2 rounded-l-full rounded-r-full'
              >GET IN TOUCH
            </a>
          </div>

        </section>

      </main>
    </div>
  )
}
